langauge: ruby
rbenv:
- 2.5.3
addons:
  postgresql: 9.6
  chrome: stable
dist: trusty
script:
- yarn
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key: 9199900f-1059-41b2-9744-33b292e78e0c
  app: brownfield-of-dreams-paired
  run: rails db:migrate
